### ISSUE TITLE
VAPP should not overwrite output files without notifying the user and offering a choice

### ISSUE THREAD

**Issue by jaijeet** [jaijeet/VAPP#4]
currently, va2modspec('vafile.va') will quietly overwrite any vafile.m that exists in the current directory.

I know this behaviour is documented - but this is a poor choice for a self-styled "UI", especially given how easy it is to do the right thing - which is to tell the user that vafile.m exists and will be overwritten, and offer a choice to go ahead or abort.

**Comment by gmahmutoglu** [comment]
This was implemented with the following commits.
ee520362 on 2017-02-27-release-github
ddfa9418 on 2017-02-27-release-github-Octave_compatible
